# Configurações do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/conecta_a_vida_db
spring.datasource.username=postgres
spring.datasource.password=20040124

# Configurações do JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true