spring.application.name=backend

# Configuração da ligação ao Supabase
spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?prepareThreshold=0&sslmode=require
spring.datasource.username=postgres.molkujbjqtmugfvtkqpo
spring.datasource.password=ConectaVida_@2121
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate (JPA) e Flyway
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.flyway.enabled=true

# Garante que o Flyway procure os scripts na pasta correta
spring.flyway.locations=classpath:db/migration