spring.application.name=backend

#DUPLIQUE ESSE ARQUIVO, TIRE 'EXEMPLO' DO NOME E MUDE A SENHA PARA A REAL. N MUDE A SENHA AQUI, POIS A SENHA N PODE SER COMITTADA.

# Configuração da ligação ao Supabase
spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres?prepareThreshold=0
spring.datasource.username=postgres.molkujbjqtmugfvtkqpo
spring.datasource.password=[SENHA_DO_PROJETO_AQUI]
spring.datasource.driver-class-name=org.postgresql.Driver

#DUPLIQUE ESSE ARQUIVO, TIRE 'EXEMPLO' DO NOME E MUDE A SENHA PARA A REAL. N MUDE A SENHA AQUI, POIS A SENHA N PODE SER COMITTADA.

# Configurações do Hibernate (JPA) e Flyway
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.flyway.enabled=true

# Garante que o Flyway procure os scripts na pasta correta
spring.flyway.locations=classpath:db/migration