# Nome da sua aplicação
spring.application.name=conectaavida-api

# ===================================================================
# CONFIGURAÇÕES DE CONEXÃO COM O SUPABASE (POOLER ATIVADO)
# ===================================================================
spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres?prepareThreshold=0
spring.datasource.username=postgres.molkujbjqtmugfvtkqpo

# Coloque sua senha real aqui (Lembre-se: remova os colchetes!)
spring.datasource.password=[senha do projeto]

spring.datasource.driver-class-name=org.postgresql.Driver

# ===================================================================
# CONFIGURAÇÕES DO HIBERNATE (JPA)
# ===================================================================
# O Hibernate agora apenas valida as entidades, não cria mais tabelas
spring.jpa.hibernate.ddl-auto=validate

# Exibe as queries formatadas no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===================================================================
# CONFIGURAÇÕES DO FLYWAY (MIGRAÇÕES DE BANCO)
# ===================================================================
# Ativa o Flyway para gerenciar a criação das tabelas via SQL
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
# Evita erros se o banco estiver vazio na primeira execução
spring.flyway.baseline-on-migrate=true

# ===================================================================
# SERVIDOR
# ===================================================================
server.port=8080
