# ===================================================================
# CONFIGURAÇÃO GERAL DA APLICAÇÃO
# ===================================================================
spring.application.name=conectaavida-api
server.port=8080

# ===================================================================
# CONFIGURAÇÃO SUPABASE - MODO SESSÃO (AWS-1 SÃO PAULO)
# ===================================================================
spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.pborxjuuexiqollesfxw
spring.datasource.password= [A sua senha do projeto]
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================================================================
# CONFIGURAÇÕES DO HIBERNATE E FLYWAY
# ===================================================================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.enabled=false

# ===================================================================
# CONFIGURAÇÕES DE ENVIO DE E-MAIL (ALERTA DE SEGURANÇA)
# ===================================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587

# E-mail que vai disparar os alertas do sistema
spring.mail.username=seu_email_remetente@gmail.com

# Senha de App de 16 dígitos sem espaços (Segurança Google)
spring.mail.password=sua_senha_de_aplicativo_google


# Propriedades de segurança SMTP obrigatórias
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Força o Java a confiar no certificado SSL da Google para evitar o erro PKIX
spring.mail.properties.mail.smtp.ssl.trust=*